### ISSUE TITLE
createGetServerSideAuth don't work

### ISSUE THREAD

**Issue by snk-js** [dferber90/aws-cognito-next-example-app#3] opened 2020-09-28 05:45 UTC
Hi, I can't any way to get the cognito auth, to verify if I'm logged, there's any other way I can do this? 

this way below don't work to me, always bring null on auth

```
export const getServerSideProps = async (context) => {
  const auth = await createGetServerSideAuth({ pems })(context.req)

  console.log('auth', auth) // result: null
};

```

**Comment by dferber90** [comment] 2020-09-28 05:50
Did you read through [this tutorial](https://medium.com/frontend-digest/authentication-in-next-js-using-amazon-cognito-f30efed6a24f?source=friends_link&sk=c68b2a89bc4d38add29f52199df80cc8) to see how to set things up?

**Comment by snk-js** [comment] 2020-09-28 18:06
> Did you read through [this tutorial](https://medium.com/frontend-digest/authentication-in-next-js-using-amazon-cognito-f30efed6a24f?source=friends_link&sk=c68b2a89bc4d38add29f52199df80cc8) to see how to set things up?

Yep, I made it work the login, but I can't hang a way to know If I'm already logged in. And that "createGetServerSideAuth" don't bring the authkeys, I tested pems, and context.req, It was suppose to work didn't? 

[EDIT]: my getServerSideProps maybe not working.  getInitialProps works, but don't know exactly why getServerSideProps can't pass data props to my component.

**Comment by dferber90** [comment] 2020-09-29 05:10
It's unlikely that this is an issue of `aws-cognito-next` itself as this part works in the demo. Make sure you're on the latest Next.js version as `getServerSideProps` was introduced recently.

It's also better to call `export const getServerSideAuth = createGetServerSideAuth({ pems })` once, and reuse the generated function as shown in the tutorial.

I'll close this issue for now as there are no concrete steps to reproduce it and it doesn't seem like this package is at fault.

Since I created this package, Amplify has added official support for server-side rendering, so you might want to look into using Amplify directly: https://github.com/aws-amplify/amplify-js/issues/5435#issuecomment-692990722

**Closed as completed by dferber90** 2020-09-29 05:10 UTC
